In [3]:
!pip install tensorflow -q

In [6]:
#scalars and tensors

import tensorflow as tf
x=tf.constant(1)
print("scalar:",x)

a=tf.constant([1,2,3])
print("1d tensor:",a)
print("shape:",a.shape)

b=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print("2d tensor:\n",b)
print("shape:", tf.rank(b))

scalar: tf.Tensor(1, shape=(), dtype=int32)
1d tensor: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
shape: (3,)
2d tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
shape: tf.Tensor(2, shape=(), dtype=int32)


In [7]:
#operations 

c=tf.constant([[1,2,3],[1,2,3],[1,2,3]])
print("addition:",tf.add(b,c))
print("multiplication:",tf.matmul(b,c))
print("element-wise multiplication", tf.multiply(b,c))

addition: tf.Tensor(
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]], shape=(3, 3), dtype=int32)
multiplication: tf.Tensor(
[[ 6 12 18]
 [15 30 45]
 [24 48 72]], shape=(3, 3), dtype=int32)
element-wise multiplication tf.Tensor(
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]], shape=(3, 3), dtype=int32)


In [8]:
#variables

v=tf.Variable(5)
print("initial:",v)
v.assign(v+1)
print("after+1:",v)
v.assign(20)
print("after assign:",v)
v.assign_add(10)
print("after assign add:",v)
v.assign_sub(5)
print("after assign sub:",v)

initial: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>
after+1: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6>
after assign: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>
after assign add: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=30>
after assign sub: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=25>


In [9]:
#reshaping
c=tf.constant([1,2,3,4,5,6])
print("reshaped:\n",tf.reshape(c,(2,3)))

#type casting
d=tf.constant([1,2,3])
print("casting:\n",tf.cast(d,tf.float32))

#shape info of matrix
matrix=tf.constant([[1,2,3,],[2,3,4],[3,4,5]])
print("shape:",tf.shape(matrix))
print("rank:",tf.rank(matrix))
print("size:",tf.size(matrix))

reshaped:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
casting:
 tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
shape: tf.Tensor([3 3], shape=(2,), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)
size: tf.Tensor(9, shape=(), dtype=int32)


In [11]:
#expanded dimensions - makes 1d into 2d
v=tf.constant([1,2,3])
print("expanded with axis=0:\n",tf.expand_dims(v,axis=0)) #o/p is 1 row 3 cols
print("expanded with axis=1:\n",tf.expand_dims(v,axis=1)) #o/p is 3 rows 1 col

expanded with axis=0:
 tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
expanded with axis=1:
 tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


In [13]:
#indexing and slicing

v1=tf.constant([1,2,3,4,5,6])
print("elem at idx 2:",v1[2].numpy())
print("slice 1-3",v1[1:3].numpy())
print("every 2nd elem:",v1[::2].numpy())
print("up to idx 3:",v1[:3].numpy())
print("from idx 2:",v1[2:].numpy())
print("----------------")
v2=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print("elem at (1,2):",v2[1,2].numpy())
print("row 0:",v2[0].numpy())
print("col 1:",v2[:,1].numpy())
print("submatrix\n",v2[0:2,1:3].numpy())
print("every 2nd row:\n",v2[::2,:].numpy())

elem at idx 2: 3
slice 1-3 [2 3]
every 2nd elem: [1 3 5]
up to idx 3: [1 2 3]
from idx 2: [3 4 5 6]
----------------
elem at (1,2): 6
row 0: [1 2 3]
col 1: [2 5 8]
submatrix
 [[2 3]
 [5 6]]
every 2nd row:
 [[1 2 3]
 [7 8 9]]
